name: Deploy Playground to GitHub Pages

on:
  push:
    branches:
      - main # 确保你的主分支名称是 main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies 🔧
        run: pnpm install

      - name: Build 🏗️
        run: pnpm build
        env:
          GITHUB_PAGES: true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: apps/playground/dist
          branch: gh-pages
